### PR TITLE
Marker popups add comments, redesigned view page

### PR DESCRIPTION
**Pull request by gecevicius**
You can now add comments through the marker popups, they dont save their locations though.
Heavily redesigned view page.
Fixed issues with affix.

### CODE REVIEW

**Comment by wilka** [comment]
👍 for the location markers.

This is more of a feature request: it'll be good if when the popup opens, the focus is in the input box so I can just start typing. Also if you don't enter a comment, then it get rid of the marker (i.e. don't show the maker & don't save an empty comment).

**Comment by wilka** [comment]
One issue with this page layout (and the previous page layout) is that it's important for the images to be displayed at actual size. The images are mostly going to be screen shots, and they need to be displayed inside in Inspicio at the same as they really are on screen, so we can review the layout, spacing, etc. properly.

At the moment, that's not what happens. For example, the screenshot (click for bigger):
image

Displayed in Inspicio (click for bigger):
image

**Review by wilka — APPROVED** [review]
This does what it's intended to do 👍

**Comment by wilka** [comment]
I'll turn my image size comment into an issue, it doesn't really belong in this review.

I'll also leave this pull request un-merged so you can sort out the merge conflicts locally (I'll be working from home on Friday, so if you want a hand with that then I'd ask @GavinHope about it)

**Comment by wilka** [comment]
I've added #3 for that image size issue.

**Comment by wilka** [comment]
Kinda related to this, if you don't want to use Bootstrap, feel free to throw it away. We also don't need to support old borwsers, so you can use [CSS grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and [Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) if you want, it'll probably make life much easier when doing layout stuff

**Comment by kerrylewis** [comment]
Agree with the comments above, and overall I think the new design is more attractive than previous versions. Other issues I found / ideas are as follows:

1) If you add multiple comments to the popup box, messages are sometimes blocked by the navigation bar. It would be better if you could adjust the comment box size to make it wider to allow for the nav bar being in the way (or something along these lines).

2) There was a previous version that allowed users to submit their comments using the enter button. This would also be nice for the popups. 

3) Could be nice to have a scrollbar to scroll through comments and prevent the whole page from moving too.

4) In the long term, it might be a nice idea to only have the first comment of a marker displayed on the side of the image. We could provide a button so that users can view the extra comments if desired (similar like threads on slack?). Depending on the volume of comments made on an image, the current system might confuse users as to which part of the interface they are referring too, and make it difficult to navigate through the comments. 

Looking forward to seeing the changes!

**Pull request merged**
