### PR TITLE
View All Page

### PR DESCRIPTION
**Pull request by kerrylewis**
Following changes made:
- Can search through results by creator as well as title.
- Description column has been removed from the view as it is no longer necessary 
- Can no longer search by description
- Creator column added to the view so you can see owns the review
- During a search, if the enter key is pressed it no longer refreshes the page
- The title column has been stretched, and all other columns are now smaller
- The ratings columns have been made significantly smaller.

### CODE REVIEW

**Review by Snappiestjack — CHANGES_REQUESTED** [review]
Initial though is that it's okay however a few small changes would be good. Set a max number of lines for the title to display, and increase the width for creator a touch. I will be setting the profilename at a max of 20 characters.

**Comment by kerrylewis** [comment]
@Snappiestjack I've sort the issue with the width of the creator column being too small, but I still need to limit the max number of lines for the description.
I looked into setting the max number of lines using the nth child, however it doesn't seem to be compatible with chrome (not ideal), and also setting a max height and making the overflow hidden (still no luck). 
An alternative would be to look into limiting the number of lines selected using c#. As I'm away tomorrow onwards feel free to look into this on my behalf!

**Comment by Snappiestjack** [comment]
@kerrylewis I've fixed these issues myself. 

Added a max character count of 125 to the title column, if the title is less than this value the whole title is displayed, if the count is over 125 characters are displayed and "..." is added to the end indicating more is hidden. 

Added a max and min length to the profile name. max is set at 16 characters, the min is 5 characters long. This is enforced when a user is first registering on the application.

@gecevicius seeing as @kerrylewis is currently away mind picking this up? :+1:

**Review by gecevicius — COMMENTED** [review]
Seems to work okay. Consider adding a maximum length to the title when creating a review?

**Review by gecevicius — APPROVED** [review]
Works!

**Review by Snappiestjack — APPROVED** [review]

**Pull request merged**
