### PR TITLE
Disabled thumbs

### PR DESCRIPTION
**Pull request by gecevicius**
Disabling thumbs on page load and on thumb click now functional.

### CODE REVIEW

**Review by Snappiestjack — CHANGES_REQUESTED** [review]
Like how the button shows it is disabled however; the button still changes when it is clicked.

image
image

**Review by Snappiestjack — CHANGES_REQUESTED** [review]
Can confirm that the issue regarding the listeners is fixed; however debug messages are left in.
image

**Comment by gecevicius** [comment]
Should be fixed now.

**Comment by Snappiestjack** [comment]
Checking now

**Review by Snappiestjack — APPROVED** [review]

**Pull request merged**
