### PR TITLE
Sorting improvements

### PR DESCRIPTION
**Pull request by Snappiestjack**
Chris has added the ability to sort the list of all reviews by; title, creator and status.

### CODE REVIEW

**Review by gecevicius — CHANGES_REQUESTED** [review]
image
Can't log in , .cshtml is missing

**Comment by Snappiestjack** [comment]
May be a issue with VS and the file explorer not updating correctly. Seems to be okay on my end. Please update.

**Comment by gecevicius** [comment]
Issue appears when entering incorrect user details.

**Comment by Snappiestjack** [comment]
See latest commit.

**Review by gecevicius — APPROVED** [review]
Works perfectly fine.

**Pull request merged**
